# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: osx
sudo: false
cache: packages
latex: false
pandoc_version: 2.3.1
disable_homebrew: true

env:
  global:
    # Do not skip tests with skip_on_cran(). Adding this to be explicit for my
    # future self. This is already set by default.
    - NOT_CRAN=true
    # Perform incoming CRAN checks that don't require remote access
    - _R_CHECK_CRAN_INCOMING_=TRUE
    - _R_CHECK_CRAN_INCOMING_REMOTE_=FALSE

script:
  - R CMD build --no-manual .
  - travis_wait 30 R CMD check --as-cran --no-examples --no-manual *tar.gz
